apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s:
      retention: 10d
        volumeClaimTemplate:
          spec:
            storageClassName: local-storage
            resources:
              requests:
                storage: 25Gi
