global:
  resolve_timeout: 5m
receivers:
  - name: 'null'
  - name: default
    email_configs:
      - to: ocp-review@example.com
        from: alerts-review@ocp4.example.com
        smarthost: '192.168.50.254:25'
        require_tls: false
route:
  group_by:
    - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: 'null'
  repeat_interval: 2m
  routes:
    - match:
        alertname: Watchdog
      receiver: 'null'
    - receiver: default
      match:
        severity: warning
